pipeline {
    agent none 
    stages{
        stage('STAGE1') {
            
            agent {label 'master'}
            steps{
                 sh '''
                    sleep 5
                    echo "This is a stage1"
                '''
            }
        }

        stage('STAGE2') {
            agent {label 'master'}
            steps{
                sh '''
                    sleep 6
                    echo "This is a stage2"
                '''
            }
        }

        stage('STAGE3') {
            agent {label 'slave3'}
            steps{
                sh '''
                    sleep 5
                    echo "This is a stage3"
                '''
            }
        }
        
        stage('STAGE4') {
            agent {label 'slave3'}
            steps{
                sh '''
                    sleep 5
                    echo "This is a stage4"
                '''
            }
        } 
       stage('STAGE5') {
           agent {label 'slave4'}
            steps{
                sh '''
                    sleep 5
                    echo "This is a stage5"
                '''
            }
        }  
    }
}

post {
    always{
    echo "this will run always"
    }
}
