pipeline {
    agent any
    
       parameters {
  string defaultValue: 'main', name: 'BRANCH', trim: true
                    }
    
    environment {
        BRANCH_NAME = "${BRANCH}"
                }
    
 
    stages{
        stage('STAGE1') {
            
            agent {label 'master'}
            steps{
                 sh '''
                    sleep 5
                    echo "This is a $BRANCH_NAME"
                '''
                 }
                      }

        stage('STAGE2') {
            agent {label 'master'}
            steps{
                sh '''
                    sleep 6
                    echo "This is a stage2"
                '''
            }
        }

        
        
        
        stage('STAGE3') {
            agent {label 'slave3'}
            
            parallel{
                
                stage('test on linux'){
            steps{
                sh '''
                    sleep 5
                    echo "This is a linux machine"
                '''
                  }
                }
                
                stage('test on windows'){
            steps{
                sh '''
                    sleep 5
                    echo "This is a windows"
                '''
                }
                }
                
                
        }
        }
            
            
            
        
        stage('STAGE4') {
            agent {label 'slave3'}
            steps{
                sh '''
                    sleep 5
                    echo "This is a stage4"
                '''
            }
        } 
       stage('STAGE5') {
           agent {label 'slave4'}
            steps{
                sh '''
                    sleep 5
                    echo "This is a stage5"
                '''
            }
        }  
    }

 post {
        always {
            echo 'This will always run'
        }
 }


}


